version: '2'
services:
    bwizjhiptest-app:
        image: bwizjhiptest
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bwizjhiptest-postgresql:5432/BwizJHipTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bwizjhiptest-postgresql:
        extends:
            file: postgresql.yml
            service: bwizjhiptest-postgresql
